/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlertEvents {
  alert_id: Int8;
  /**
   * Date of the data behind the event: the session, earnings report, filing or screener snapshot.
   */
  bar_date: string;
  delivered_at: Timestamp | null;
  delivery_status: Generated<string>;
  error: string | null;
  event_id: Generated<Int8>;
  event_key: string;
  fired_at: Generated<Timestamp>;
  message: string;
  user_id: string;
}

export interface Alerts {
  active: Generated<boolean>;
  alert_id: Generated<Int8>;
  cooldown_hours: Generated<number>;
  created_at: Generated<Timestamp>;
  kind: string;
  last_fired_at: Timestamp | null;
  params: Generated<Json>;
  screen_id: Int8 | null;
  security_id: Int8 | null;
  snoozed_until: Timestamp | null;
  state: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuditLogs {
  action: string;
  at: Generated<Timestamp>;
  audit_id: Generated<Int8>;
  details: Generated<Json>;
  entity: string | null;
  entity_id: string | null;
  user_id: string | null;
}

export interface BacktestResults {
  created_at: Generated<Timestamp>;
  inputs: Json;
  report: Json | null;
  run_id: Int8;
  summary: Json;
  user_id: string;
  validation: Json | null;
}

export interface BacktestRuns {
  code_version: string | null;
  created_at: Generated<Timestamp>;
  data_snapshot_id: string | null;
  error: string | null;
  finished_at: Timestamp | null;
  kind: string;
  name: string;
  request: Json;
  run_id: Generated<Int8>;
  started_at: Timestamp | null;
  status: Generated<string>;
  strategy_id: Int8 | null;
  user_id: string;
}

export interface ChartDrawings {
  basis: string;
  created_at: Generated<Timestamp>;
  drawing_id: Generated<Int8>;
  kind: string;
  label: string | null;
  points: Json;
  security_id: Int8;
  user_id: string;
}

export interface DashboardLayouts {
  layout: Json;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MarketAdjustmentFactors {
  computed_at: Generated<Timestamp>;
  dividend_factor: number;
  ex_date: string;
  security_id: Int8;
  split_factor: number;
}

export interface MarketCorporateActions {
  action_id: Generated<Int8>;
  cash_amount: Numeric | null;
  currency: string | null;
  details: Generated<Json>;
  ex_date: string;
  ingested_at: Generated<Timestamp>;
  pay_date: string | null;
  /**
   * New shares per old share: 4 for a 4:1 split, 0.1 for a 1:10 reverse split, 1.05 for a 5% stock dividend.
   */
  ratio: Numeric | null;
  record_date: string | null;
  security_id: Int8;
  source: string;
  type: string;
}

export interface MarketDataProviders {
  display_name: string;
  kind: string;
  provider_id: string;
}

export interface MarketEarningsEvents {
  eps_actual: Numeric | null;
  eps_estimate: Numeric | null;
  fetched_at: Timestamp;
  fiscal_quarter: number | null;
  fiscal_year: number | null;
  /**
   * bmo: before the open; amc: after the close; dmh: during market hours.
   */
  hour: string | null;
  report_date: string;
  revenue_actual: Numeric | null;
  revenue_estimate: Numeric | null;
  security_id: Int8;
  source: string;
}

export interface MarketEconomicReleases {
  fetched_at: Timestamp;
  name: string;
  release_date: string;
  release_id: number;
  source: string;
}

export interface MarketFilings {
  accession_no: string;
  cik: string;
  /**
   * EDGAR acceptance time: when the filing became public.
   */
  filed_at: Timestamp;
  filing_date: string;
  form_type: string;
  ingested_at: Generated<Timestamp>;
  items: Generated<string[]>;
  period: string | null;
  primary_document: string | null;
  source: string;
  storage_path: string | null;
  summary_status: Generated<string>;
  url: string;
}

export interface MarketFinancialStatements {
  basis: string;
  built_at: Generated<Timestamp>;
  cik: string;
  fiscal_period: string;
  fiscal_year: number;
  frequency: string;
  /**
   * Map of line id to {value (decimal string), concept, unit, accession, filed, derived?}.
   */
  line_items: Json;
  period_end: string;
  period_start: string | null;
  restated: Generated<boolean>;
  source: string;
  statement: string;
}

export interface MarketForm13fDataSets {
  filings: number;
  holdings: number;
  infotable_rows: Int8;
  ingested_at: Timestamp;
  name: string;
  row_count_mismatches: Generated<string[]>;
  url: string;
  window_end: string;
  window_start: string;
}

export interface MarketForm13fFilings {
  accession_no: string;
  amendment_type: string | null;
  data_set: string;
  filed_on: string;
  filer_cik: string;
  filer_name: string;
  report_period: string;
  report_type: string;
  submission_type: string;
  table_entry_total: number | null;
  table_value_total: Numeric | null;
}

export interface MarketForm13fHoldings {
  accession_no: string;
  cusip: string;
  rows: number;
  security_id: Int8;
  shares: Numeric;
  value_usd: Numeric;
}

export interface MarketFundamentalsFacts {
  accession_no: string;
  cik: string;
  concept: string;
  /**
   * EDGAR filing date (date only).
   */
  filed_at: string;
  fiscal_period: string | null;
  fiscal_year: number | null;
  form: string;
  frame: string | null;
  ingested_at: Generated<Timestamp>;
  period_end: string;
  period_start: string | null;
  source: string;
  taxonomy: string;
  unit: string;
  value: Numeric;
}

export interface MarketInsiderFilingErrors {
  accession_no: string;
  cik: string;
  error: string;
  failed_at: Generated<Timestamp>;
  parser_version: number;
}

export interface MarketInsiderFilings {
  accession_no: string;
  /**
   * The Rule 10b5-1(c) check box; null on filings made before the box existed (2023).
   */
  aff_10b5_1: boolean | null;
  fetched_at: Timestamp;
  filed_at: Timestamp;
  footnotes: Generated<Json>;
  form_type: string;
  issuer_cik: string;
  issuer_name: string;
  issuer_symbol: string | null;
  no_longer_subject_to_section16: Generated<boolean>;
  original_filing_date: string | null;
  /**
   * Reporting owners as filed: [{cik, name, is_director, is_officer, officer_title, is_ten_percent_owner, is_other, other_text}].
   */
  owners: Json;
  parser_version: number;
  period_of_report: string;
  remarks: string | null;
  schema_version: string | null;
  source: Generated<string>;
  url: string;
}

export interface MarketInsiderTransactions {
  accession_no: string;
  acquired_disposed: string | null;
  code: string;
  conversion_price: Numeric | null;
  deemed_execution_date: string | null;
  derivative: boolean;
  equity_swap: Generated<boolean>;
  exercise_date: string | null;
  expiration_date: string | null;
  footnote_ids: Generated<string[]>;
  line: number;
  ownership: string | null;
  ownership_nature: string | null;
  price: Numeric | null;
  security_title: string;
  shares: Numeric | null;
  /**
   * Shares held after this line on its own ownership line (direct, or one indirect holding).
   */
  shares_after: Numeric | null;
  transaction_date: string;
  underlying_shares: Numeric | null;
  underlying_title: string | null;
}

export interface MarketInstitutionalHoldings {
  accession_nos: string[];
  filed_on: string;
  filer_cik: string;
  filer_name: string;
  report_period: string;
  security_id: Int8;
  shares: Numeric;
  value_usd: Numeric;
}

export interface MarketMacroObservations {
  date: string;
  ingested_at: Generated<Timestamp>;
  realtime_start: string;
  series_id: string;
  value: Numeric | null;
}

export interface MarketMacroSeries {
  frequency: string | null;
  ingested_at: Generated<Timestamp>;
  last_updated: Timestamp | null;
  observation_end: string | null;
  observation_start: string | null;
  seasonal_adjustment: string | null;
  series_id: string;
  source: string;
  title: string;
  units: string | null;
}

export interface MarketPricesDaily {
  close: Numeric;
  date: string;
  high: Numeric;
  ingested_at: Generated<Timestamp>;
  ingestion_run_id: Int8 | null;
  low: Numeric;
  open: Numeric;
  security_id: Int8;
  source: string;
  volume: Int8;
  vwap: Numeric | null;
}

export interface MarketPricesDailyAdjusted {
  close: number | null;
  date: string | null;
  dividend_factor: number | null;
  high: number | null;
  low: number | null;
  open: number | null;
  security_id: Int8 | null;
  source: string | null;
  split_factor: number | null;
  volume: number | null;
}

export interface MarketProviderSymbols {
  security_id: Int8;
  source: string;
  /**
   * Vendor permanent identifier, when the vendor has one.
   */
  source_security_id: string | null;
  source_symbol: string;
  valid_from: string;
  valid_to: string | null;
}

export interface MarketScreenerSnapshot {
  as_of: string;
  asset_class: string;
  avg_volume_30d: number | null;
  change_1d: number | null;
  close: Numeric;
  dividend_yield: number | null;
  equity: Numeric | null;
  exchange_mic: string | null;
  fundamentals_as_of: string | null;
  high_52w: number | null;
  industry: string | null;
  low_52w: number | null;
  market_cap: number | null;
  name: string;
  net_income_ttm: Numeric | null;
  pb: number | null;
  pe: number | null;
  ps: number | null;
  refreshed_at: Generated<Timestamp>;
  return_1m: number | null;
  return_1w: number | null;
  return_1y: number | null;
  return_3m: number | null;
  return_6m: number | null;
  return_ytd: number | null;
  revenue_ttm: Numeric | null;
  rsi14: number | null;
  sector: string | null;
  security_id: Int8;
  shares_outstanding: Numeric | null;
  sma200: number | null;
  sma50: number | null;
  source: string;
  ticker: string;
}

export interface MarketSecurities {
  asset_class: string;
  cik: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  delisted_at: string | null;
  exchange_mic: string | null;
  figi: string | null;
  industry: string | null;
  is_active: Generated<boolean>;
  listed_at: string | null;
  name: string;
  sector: string | null;
  security_id: Generated<Int8>;
  /**
   * SEC Standard Industrial Classification code from EDGAR submissions.
   */
  sic_code: string | null;
  /**
   * Current (or last) ticker; history lives in security_symbol_history.
   */
  ticker: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketSecurityCusips {
  cusip: string;
  /**
   * The issue name in the fails-to-deliver file (SEC cuts it to 30 characters).
   */
  description: string;
  first_seen: string;
  last_seen: string;
  security_id: Int8;
  source: Generated<string>;
  symbol: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketSecuritySymbolHistory {
  security_id: Int8;
  ticker: string;
  valid_from: string;
  valid_to: string | null;
}

export interface Notifications {
  body: Generated<string>;
  created_at: Generated<Timestamp>;
  event_id: Int8;
  href: string | null;
  notification_id: Generated<Int8>;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface OpsAlerts {
  alert_id: Generated<Int8>;
  dataset: string;
  details: Generated<Json>;
  kind: string;
  last_seen_at: Generated<Timestamp>;
  message: string;
  opened_at: Generated<Timestamp>;
  resolved_at: Timestamp | null;
  severity: string;
  source: string | null;
}

export interface OpsDataCorrections {
  correction_id: Generated<Int8>;
  date: string;
  detected_at: Generated<Timestamp>;
  new_values: Json;
  old_values: Json;
  run_id: Int8 | null;
  security_id: Int8;
  source: string;
}

export interface OpsDataIngestionRuns {
  dataset: string;
  error: string | null;
  finished_at: Timestamp | null;
  http_status_counts: Generated<Json>;
  job_id: string | null;
  job_name: string;
  params: Generated<Json>;
  rows_fetched: Generated<number>;
  rows_flagged: Generated<number>;
  rows_inserted: Generated<number>;
  rows_rejected: Generated<number>;
  rows_unchanged: Generated<number>;
  rows_updated: Generated<number>;
  run_id: Generated<Int8>;
  source: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface OpsDataQualityIssues {
  action: string;
  created_at: Generated<Timestamp>;
  dataset: string;
  date: string | null;
  issue_id: Generated<Int8>;
  message: string;
  payload: Generated<Json>;
  resolved_at: Timestamp | null;
  rule: string;
  run_id: Int8 | null;
  security_id: Int8 | null;
  severity: string;
  source: string | null;
  status: Generated<string>;
}

export interface OpsDatasetRouting {
  active_source: string | null;
  dataset: string;
  failed_over_at: Timestamp | null;
  fallback_source: string | null;
  primary_source: string;
  reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OpsFeatureFlags {
  enabled: boolean;
  key: string;
  updated_at: Generated<Timestamp>;
}

export interface OpsProviderHealth {
  consecutive_failures: Generated<number>;
  consecutive_successes: Generated<number>;
  dataset: string;
  failures_total: Generated<Int8>;
  last_error: string | null;
  last_failure_at: Timestamp | null;
  last_latency_ms: number | null;
  last_success_at: Timestamp | null;
  requests_total: Generated<Int8>;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface Portfolios {
  base_currency: Generated<string>;
  benchmark_ticker: Generated<string>;
  created_at: Generated<Timestamp>;
  name: string;
  portfolio_id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface SavedScreens {
  created_at: Generated<Timestamp>;
  definition: Json;
  name: string;
  screen_id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Strategies {
  created_at: Generated<Timestamp>;
  definition: Json;
  name: string;
  strategy_id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Transactions {
  amount: Numeric | null;
  created_at: Generated<Timestamp>;
  fees: Generated<Numeric>;
  notes: string | null;
  portfolio_id: Int8;
  price: Numeric | null;
  quantity: Numeric | null;
  security_id: Int8 | null;
  source: Generated<string>;
  trade_date: string;
  transaction_id: Generated<Int8>;
  type: string;
  user_id: string;
}

export interface ValuationScenarios {
  created_at: Generated<Timestamp>;
  inputs: Json;
  name: string;
  scenario_id: Generated<Int8>;
  security_id: Int8;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface WatchlistItems {
  added_at: Generated<Timestamp>;
  position: Generated<number>;
  security_id: Int8;
  user_id: string;
  watchlist_id: Int8;
}

export interface Watchlists {
  created_at: Generated<Timestamp>;
  name: string;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  watchlist_id: Generated<Int8>;
}

export interface DB {
  alert_events: AlertEvents;
  alerts: Alerts;
  audit_logs: AuditLogs;
  backtest_results: BacktestResults;
  backtest_runs: BacktestRuns;
  chart_drawings: ChartDrawings;
  dashboard_layouts: DashboardLayouts;
  "market.adjustment_factors": MarketAdjustmentFactors;
  "market.corporate_actions": MarketCorporateActions;
  "market.data_providers": MarketDataProviders;
  "market.earnings_events": MarketEarningsEvents;
  "market.economic_releases": MarketEconomicReleases;
  "market.filings": MarketFilings;
  "market.financial_statements": MarketFinancialStatements;
  "market.form13f_data_sets": MarketForm13fDataSets;
  "market.form13f_filings": MarketForm13fFilings;
  "market.form13f_holdings": MarketForm13fHoldings;
  "market.fundamentals_facts": MarketFundamentalsFacts;
  "market.insider_filing_errors": MarketInsiderFilingErrors;
  "market.insider_filings": MarketInsiderFilings;
  "market.insider_transactions": MarketInsiderTransactions;
  "market.institutional_holdings": MarketInstitutionalHoldings;
  "market.macro_observations": MarketMacroObservations;
  "market.macro_series": MarketMacroSeries;
  "market.prices_daily": MarketPricesDaily;
  "market.prices_daily_adjusted": MarketPricesDailyAdjusted;
  "market.provider_symbols": MarketProviderSymbols;
  "market.screener_snapshot": MarketScreenerSnapshot;
  "market.securities": MarketSecurities;
  "market.security_cusips": MarketSecurityCusips;
  "market.security_symbol_history": MarketSecuritySymbolHistory;
  notifications: Notifications;
  "ops.alerts": OpsAlerts;
  "ops.data_corrections": OpsDataCorrections;
  "ops.data_ingestion_runs": OpsDataIngestionRuns;
  "ops.data_quality_issues": OpsDataQualityIssues;
  "ops.dataset_routing": OpsDatasetRouting;
  "ops.feature_flags": OpsFeatureFlags;
  "ops.provider_health": OpsProviderHealth;
  portfolios: Portfolios;
  saved_screens: SavedScreens;
  strategies: Strategies;
  transactions: Transactions;
  valuation_scenarios: ValuationScenarios;
  watchlist_items: WatchlistItems;
  watchlists: Watchlists;
}
