/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MarketAdjustmentFactors {
  computed_at: Generated<Timestamp>;
  dividend_factor: number;
  ex_date: string;
  security_id: Int8;
  split_factor: number;
}

export interface MarketCorporateActions {
  action_id: Generated<Int8>;
  cash_amount: Numeric | null;
  currency: string | null;
  details: Generated<Json>;
  ex_date: string;
  ingested_at: Generated<Timestamp>;
  pay_date: string | null;
  /**
   * New shares per old share: 4 for a 4:1 split, 0.1 for a 1:10 reverse split, 1.05 for a 5% stock dividend.
   */
  ratio: Numeric | null;
  record_date: string | null;
  security_id: Int8;
  source: string;
  type: string;
}

export interface MarketDataProviders {
  display_name: string;
  kind: string;
  provider_id: string;
}

export interface MarketFilings {
  accession_no: string;
  cik: string;
  /**
   * EDGAR acceptance time: when the filing became public.
   */
  filed_at: Timestamp;
  filing_date: string;
  form_type: string;
  ingested_at: Generated<Timestamp>;
  items: Generated<string[]>;
  period: string | null;
  primary_document: string | null;
  source: string;
  storage_path: string | null;
  summary_status: Generated<string>;
  url: string;
}

export interface MarketFundamentalsFacts {
  accession_no: string;
  cik: string;
  concept: string;
  /**
   * EDGAR filing date (date only).
   */
  filed_at: string;
  fiscal_period: string | null;
  fiscal_year: number | null;
  form: string;
  frame: string | null;
  ingested_at: Generated<Timestamp>;
  period_end: string;
  period_start: string | null;
  source: string;
  taxonomy: string;
  unit: string;
  value: Numeric;
}

export interface MarketMacroObservations {
  date: string;
  ingested_at: Generated<Timestamp>;
  realtime_start: string;
  series_id: string;
  value: Numeric | null;
}

export interface MarketMacroSeries {
  frequency: string | null;
  ingested_at: Generated<Timestamp>;
  last_updated: Timestamp | null;
  observation_end: string | null;
  observation_start: string | null;
  seasonal_adjustment: string | null;
  series_id: string;
  source: string;
  title: string;
  units: string | null;
}

export interface MarketPricesDaily {
  close: Numeric;
  date: string;
  high: Numeric;
  ingested_at: Generated<Timestamp>;
  ingestion_run_id: Int8 | null;
  low: Numeric;
  open: Numeric;
  security_id: Int8;
  source: string;
  volume: Int8;
  vwap: Numeric | null;
}

export interface MarketPricesDailyAdjusted {
  close: number | null;
  date: string | null;
  dividend_factor: number | null;
  high: number | null;
  low: number | null;
  open: number | null;
  security_id: Int8 | null;
  source: string | null;
  split_factor: number | null;
  volume: number | null;
}

export interface MarketProviderSymbols {
  security_id: Int8;
  source: string;
  /**
   * Vendor permanent identifier, when the vendor has one.
   */
  source_security_id: string | null;
  source_symbol: string;
  valid_from: string;
  valid_to: string | null;
}

export interface MarketSecurities {
  asset_class: string;
  cik: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  delisted_at: string | null;
  exchange_mic: string | null;
  figi: string | null;
  industry: string | null;
  is_active: Generated<boolean>;
  listed_at: string | null;
  name: string;
  sector: string | null;
  security_id: Generated<Int8>;
  /**
   * Current (or last) ticker; history lives in security_symbol_history.
   */
  ticker: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketSecuritySymbolHistory {
  security_id: Int8;
  ticker: string;
  valid_from: string;
  valid_to: string | null;
}

export interface OpsAlerts {
  alert_id: Generated<Int8>;
  dataset: string;
  details: Generated<Json>;
  kind: string;
  last_seen_at: Generated<Timestamp>;
  message: string;
  opened_at: Generated<Timestamp>;
  resolved_at: Timestamp | null;
  severity: string;
  source: string | null;
}

export interface OpsDataCorrections {
  correction_id: Generated<Int8>;
  date: string;
  detected_at: Generated<Timestamp>;
  new_values: Json;
  old_values: Json;
  run_id: Int8 | null;
  security_id: Int8;
  source: string;
}

export interface OpsDataIngestionRuns {
  dataset: string;
  error: string | null;
  finished_at: Timestamp | null;
  http_status_counts: Generated<Json>;
  job_id: string | null;
  job_name: string;
  params: Generated<Json>;
  rows_fetched: Generated<number>;
  rows_flagged: Generated<number>;
  rows_inserted: Generated<number>;
  rows_rejected: Generated<number>;
  rows_unchanged: Generated<number>;
  rows_updated: Generated<number>;
  run_id: Generated<Int8>;
  source: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface OpsDataQualityIssues {
  action: string;
  created_at: Generated<Timestamp>;
  dataset: string;
  date: string | null;
  issue_id: Generated<Int8>;
  message: string;
  payload: Generated<Json>;
  resolved_at: Timestamp | null;
  rule: string;
  run_id: Int8 | null;
  security_id: Int8 | null;
  severity: string;
  source: string | null;
  status: Generated<string>;
}

export interface OpsDatasetRouting {
  active_source: string | null;
  dataset: string;
  failed_over_at: Timestamp | null;
  fallback_source: string | null;
  primary_source: string;
  reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OpsProviderHealth {
  consecutive_failures: Generated<number>;
  dataset: string;
  failures_total: Generated<Int8>;
  last_error: string | null;
  last_failure_at: Timestamp | null;
  last_latency_ms: number | null;
  last_success_at: Timestamp | null;
  requests_total: Generated<Int8>;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "market.adjustment_factors": MarketAdjustmentFactors;
  "market.corporate_actions": MarketCorporateActions;
  "market.data_providers": MarketDataProviders;
  "market.filings": MarketFilings;
  "market.fundamentals_facts": MarketFundamentalsFacts;
  "market.macro_observations": MarketMacroObservations;
  "market.macro_series": MarketMacroSeries;
  "market.prices_daily": MarketPricesDaily;
  "market.prices_daily_adjusted": MarketPricesDailyAdjusted;
  "market.provider_symbols": MarketProviderSymbols;
  "market.securities": MarketSecurities;
  "market.security_symbol_history": MarketSecuritySymbolHistory;
  "ops.alerts": OpsAlerts;
  "ops.data_corrections": OpsDataCorrections;
  "ops.data_ingestion_runs": OpsDataIngestionRuns;
  "ops.data_quality_issues": OpsDataQualityIssues;
  "ops.dataset_routing": OpsDatasetRouting;
  "ops.provider_health": OpsProviderHealth;
}
